# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_geosearch.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GeoSearch(object):
    def setupUi(self, GeoSearch):
        GeoSearch.setObjectName(_fromUtf8("GeoSearch"))
        GeoSearch.resize(587, 508)
        self.FeatureOption_tabWidget = QtGui.QTabWidget(GeoSearch)
        self.FeatureOption_tabWidget.setGeometry(QtCore.QRect(0, 0, 581, 500))
        self.FeatureOption_tabWidget.setObjectName(_fromUtf8("FeatureOption_tabWidget"))
        self.Pt_tab = QtGui.QWidget()
        self.Pt_tab.setObjectName(_fromUtf8("Pt_tab"))
        self.latitude_label = QtGui.QLabel(self.Pt_tab)
        self.latitude_label.setGeometry(QtCore.QRect(190, 60, 51, 16))
        self.latitude_label.setObjectName(_fromUtf8("latitude_label"))
        self.Longitude_label = QtGui.QLabel(self.Pt_tab)
        self.Longitude_label.setGeometry(QtCore.QRect(290, 60, 61, 16))
        self.Longitude_label.setObjectName(_fromUtf8("Longitude_label"))
        self.ExactOneResult_checkBox = QtGui.QCheckBox(self.Pt_tab)
        self.ExactOneResult_checkBox.setGeometry(QtCore.QRect(380, 110, 131, 17))
        self.ExactOneResult_checkBox.setChecked(True)
        self.ExactOneResult_checkBox.setObjectName(_fromUtf8("ExactOneResult_checkBox"))
        self.SearchByAddr_pushButton = QtGui.QPushButton(self.Pt_tab)
        self.SearchByAddr_pushButton.setGeometry(QtCore.QRect(430, 30, 81, 23))
        self.SearchByAddr_pushButton.setObjectName(_fromUtf8("SearchByAddr_pushButton"))
        self.Geocoder_Addr_label_2 = QtGui.QLabel(self.Pt_tab)
        self.Geocoder_Addr_label_2.setGeometry(QtCore.QRect(50, 60, 61, 16))
        self.Geocoder_Addr_label_2.setObjectName(_fromUtf8("Geocoder_Addr_label_2"))
        self.GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.Pt_tab)
        self.GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(380, 80, 91, 23))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.GoToGetCoorFromMapCanvasMode_pushButton.setFont(font)
        self.GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Latitude_lineEdit = QtGui.QLineEdit(self.Pt_tab)
        self.Latitude_lineEdit.setGeometry(QtCore.QRect(160, 80, 101, 20))
        self.Latitude_lineEdit.setObjectName(_fromUtf8("Latitude_lineEdit"))
        self.Geocoder_Addr_comboBox = QtGui.QComboBox(self.Pt_tab)
        self.Geocoder_Addr_comboBox.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.Geocoder_Addr_comboBox.setObjectName(_fromUtf8("Geocoder_Addr_comboBox"))
        self.Addr_lineEdit = QtGui.QLineEdit(self.Pt_tab)
        self.Addr_lineEdit.setGeometry(QtCore.QRect(162, 30, 261, 20))
        self.Addr_lineEdit.setObjectName(_fromUtf8("Addr_lineEdit"))
        self.Longitude_lineEdit = QtGui.QLineEdit(self.Pt_tab)
        self.Longitude_lineEdit.setGeometry(QtCore.QRect(270, 80, 101, 20))
        self.Longitude_lineEdit.setObjectName(_fromUtf8("Longitude_lineEdit"))
        self.Geocoder_Pt_comboBox = QtGui.QComboBox(self.Pt_tab)
        self.Geocoder_Pt_comboBox.setGeometry(QtCore.QRect(10, 80, 141, 22))
        self.Geocoder_Pt_comboBox.setObjectName(_fromUtf8("Geocoder_Pt_comboBox"))
        self.SearchByPt_pushButton = QtGui.QPushButton(self.Pt_tab)
        self.SearchByPt_pushButton.setGeometry(QtCore.QRect(480, 80, 71, 23))
        self.SearchByPt_pushButton.setObjectName(_fromUtf8("SearchByPt_pushButton"))
        self.Address_label = QtGui.QLabel(self.Pt_tab)
        self.Address_label.setGeometry(QtCore.QRect(250, 10, 46, 13))
        self.Address_label.setObjectName(_fromUtf8("Address_label"))
        self.Geocoder_Addr_label = QtGui.QLabel(self.Pt_tab)
        self.Geocoder_Addr_label.setGeometry(QtCore.QRect(50, 10, 61, 16))
        self.Geocoder_Addr_label.setObjectName(_fromUtf8("Geocoder_Addr_label"))
        self.SearchStatus_label = QtGui.QLabel(self.Pt_tab)
        self.SearchStatus_label.setGeometry(QtCore.QRect(240, 160, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SearchStatus_label.setFont(font)
        self.SearchStatus_label.setObjectName(_fromUtf8("SearchStatus_label"))
        self.Result_tabWidget = QtGui.QTabWidget(self.Pt_tab)
        self.Result_tabWidget.setGeometry(QtCore.QRect(30, 170, 511, 281))
        self.Result_tabWidget.setObjectName(_fromUtf8("Result_tabWidget"))
        self.List_tab = QtGui.QWidget()
        self.List_tab.setObjectName(_fromUtf8("List_tab"))
        self.Result_List_label = QtGui.QLabel(self.List_tab)
        self.Result_List_label.setGeometry(QtCore.QRect(10, 30, 221, 16))
        self.Result_List_label.setObjectName(_fromUtf8("Result_List_label"))
        self.Result_listWidget = QtGui.QListWidget(self.List_tab)
        self.Result_listWidget.setGeometry(QtCore.QRect(10, 50, 481, 201))
        self.Result_listWidget.setObjectName(_fromUtf8("Result_listWidget"))
        self.Result_tabWidget.addTab(self.List_tab, _fromUtf8(""))
        self.Text_tab = QtGui.QWidget()
        self.Text_tab.setObjectName(_fromUtf8("Text_tab"))
        self.Result_textEdit = QtGui.QTextEdit(self.Text_tab)
        self.Result_textEdit.setGeometry(QtCore.QRect(10, 50, 481, 201))
        self.Result_textEdit.setObjectName(_fromUtf8("Result_textEdit"))
        self.Result_List_label_2 = QtGui.QLabel(self.Text_tab)
        self.Result_List_label_2.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.Result_List_label_2.setObjectName(_fromUtf8("Result_List_label_2"))
        self.Result_tabWidget.addTab(self.Text_tab, _fromUtf8(""))
        self.SearchOnGoogleWebMap_checkBox = QtGui.QCheckBox(self.Pt_tab)
        self.SearchOnGoogleWebMap_checkBox.setEnabled(True)
        self.SearchOnGoogleWebMap_checkBox.setGeometry(QtCore.QRect(380, 150, 191, 20))
        self.SearchOnGoogleWebMap_checkBox.setChecked(False)
        self.SearchOnGoogleWebMap_checkBox.setObjectName(_fromUtf8("SearchOnGoogleWebMap_checkBox"))
        self.ObtainElevation_checkBox = QtGui.QCheckBox(self.Pt_tab)
        self.ObtainElevation_checkBox.setEnabled(True)
        self.ObtainElevation_checkBox.setGeometry(QtCore.QRect(380, 130, 131, 20))
        self.ObtainElevation_checkBox.setChecked(False)
        self.ObtainElevation_checkBox.setObjectName(_fromUtf8("ObtainElevation_checkBox"))
        self.ResultFmt_label = QtGui.QLabel(self.Pt_tab)
        self.ResultFmt_label.setGeometry(QtCore.QRect(130, 200, 261, 20))
        self.ResultFmt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultFmt_label.setObjectName(_fromUtf8("ResultFmt_label"))
        self.FeatureOption_tabWidget.addTab(self.Pt_tab, _fromUtf8(""))
        self.Distance_tab = QtGui.QWidget()
        self.Distance_tab.setObjectName(_fromUtf8("Distance_tab"))
        self.CalculateDist_pushButton = QtGui.QPushButton(self.Distance_tab)
        self.CalculateDist_pushButton.setGeometry(QtCore.QRect(230, 150, 71, 23))
        self.CalculateDist_pushButton.setObjectName(_fromUtf8("CalculateDist_pushButton"))
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.Distance_tab)
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(350, 90, 91, 23))
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Dist_latitude_label = QtGui.QLabel(self.Distance_tab)
        self.Dist_latitude_label.setGeometry(QtCore.QRect(160, 70, 51, 16))
        self.Dist_latitude_label.setObjectName(_fromUtf8("Dist_latitude_label"))
        self.Dist_Longitude_label = QtGui.QLabel(self.Distance_tab)
        self.Dist_Longitude_label.setGeometry(QtCore.QRect(260, 70, 61, 16))
        self.Dist_Longitude_label.setObjectName(_fromUtf8("Dist_Longitude_label"))
        self.DistFomula_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.DistFomula_comboBox.setGeometry(QtCore.QRect(130, 30, 141, 22))
        self.DistFomula_comboBox.setObjectName(_fromUtf8("DistFomula_comboBox"))
        self.Dist_PtA_Latitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtA_Latitude_lineEdit.setGeometry(QtCore.QRect(130, 90, 101, 20))
        self.Dist_PtA_Latitude_lineEdit.setObjectName(_fromUtf8("Dist_PtA_Latitude_lineEdit"))
        self.DistFormula_label = QtGui.QLabel(self.Distance_tab)
        self.DistFormula_label.setGeometry(QtCore.QRect(170, 10, 51, 16))
        self.DistFormula_label.setObjectName(_fromUtf8("DistFormula_label"))
        self.Dist_PtA_Longitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtA_Longitude_lineEdit.setGeometry(QtCore.QRect(240, 90, 101, 20))
        self.Dist_PtA_Longitude_lineEdit.setObjectName(_fromUtf8("Dist_PtA_Longitude_lineEdit"))
        self.VincentyElliModel_label = QtGui.QLabel(self.Distance_tab)
        self.VincentyElliModel_label.setGeometry(QtCore.QRect(280, 10, 170, 20))
        self.VincentyElliModel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VincentyElliModel_label.setObjectName(_fromUtf8("VincentyElliModel_label"))
        self.VctElliModel_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.VctElliModel_comboBox.setGeometry(QtCore.QRect(280, 30, 161, 22))
        self.VctElliModel_comboBox.setObjectName(_fromUtf8("VctElliModel_comboBox"))
        self.PtA_label = QtGui.QLabel(self.Distance_tab)
        self.PtA_label.setGeometry(QtCore.QRect(75, 90, 51, 20))
        self.PtA_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PtA_label.setObjectName(_fromUtf8("PtA_label"))
        self.Dist_PtB_Latitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtB_Latitude_lineEdit.setGeometry(QtCore.QRect(130, 120, 101, 20))
        self.Dist_PtB_Latitude_lineEdit.setObjectName(_fromUtf8("Dist_PtB_Latitude_lineEdit"))
        self.PtB_label = QtGui.QLabel(self.Distance_tab)
        self.PtB_label.setGeometry(QtCore.QRect(75, 120, 51, 20))
        self.PtB_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PtB_label.setObjectName(_fromUtf8("PtB_label"))
        self.Dist_PtB_Longitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtB_Longitude_lineEdit.setGeometry(QtCore.QRect(240, 120, 101, 20))
        self.Dist_PtB_Longitude_lineEdit.setObjectName(_fromUtf8("Dist_PtB_Longitude_lineEdit"))
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.Distance_tab)
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(350, 120, 91, 23))
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Dist_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_lineEdit.setGeometry(QtCore.QRect(190, 190, 141, 20))
        self.Dist_lineEdit.setObjectName(_fromUtf8("Dist_lineEdit"))
        self.Dist_label = QtGui.QLabel(self.Distance_tab)
        self.Dist_label.setGeometry(QtCore.QRect(135, 190, 51, 20))
        self.Dist_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Dist_label.setObjectName(_fromUtf8("Dist_label"))
        self.DistUnit_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.DistUnit_comboBox.setGeometry(QtCore.QRect(340, 190, 111, 22))
        self.DistUnit_comboBox.setObjectName(_fromUtf8("DistUnit_comboBox"))
        self.Bearing_label = QtGui.QLabel(self.Distance_tab)
        self.Bearing_label.setGeometry(QtCore.QRect(135, 220, 51, 20))
        self.Bearing_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Bearing_label.setObjectName(_fromUtf8("Bearing_label"))
        self.Bearing_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Bearing_lineEdit.setGeometry(QtCore.QRect(190, 220, 141, 20))
        self.Bearing_lineEdit.setObjectName(_fromUtf8("Bearing_lineEdit"))
        self.BearingUnit_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.BearingUnit_comboBox.setGeometry(QtCore.QRect(340, 220, 111, 22))
        self.BearingUnit_comboBox.setObjectName(_fromUtf8("BearingUnit_comboBox"))
        self.BearingIsPositiveOnly_checkBox = QtGui.QCheckBox(self.Distance_tab)
        self.BearingIsPositiveOnly_checkBox.setEnabled(True)
        self.BearingIsPositiveOnly_checkBox.setGeometry(QtCore.QRect(460, 220, 101, 20))
        self.BearingIsPositiveOnly_checkBox.setChecked(False)
        self.BearingIsPositiveOnly_checkBox.setObjectName(_fromUtf8("BearingIsPositiveOnly_checkBox"))
        self.FeatureOption_tabWidget.addTab(self.Distance_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.RoutePoints_textEdit = QtGui.QTextEdit(self.tab)
        self.RoutePoints_textEdit.setGeometry(QtCore.QRect(10, 50, 321, 171))
        self.RoutePoints_textEdit.setObjectName(_fromUtf8("RoutePoints_textEdit"))
        self.RoutePointsFmt_label = QtGui.QLabel(self.tab)
        self.RoutePointsFmt_label.setGeometry(QtCore.QRect(40, 30, 261, 20))
        self.RoutePointsFmt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RoutePointsFmt_label.setObjectName(_fromUtf8("RoutePointsFmt_label"))
        self.RoutePoints_label = QtGui.QLabel(self.tab)
        self.RoutePoints_label.setGeometry(QtCore.QRect(130, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RoutePoints_label.setFont(font)
        self.RoutePoints_label.setObjectName(_fromUtf8("RoutePoints_label"))
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.tab)
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(360, 180, 91, 23))
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("Route_GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Route_TravelMode_comboBox = QtGui.QComboBox(self.tab)
        self.Route_TravelMode_comboBox.setGeometry(QtCore.QRect(440, 50, 111, 22))
        self.Route_TravelMode_comboBox.setObjectName(_fromUtf8("Route_TravelMode_comboBox"))
        self.TravelMode_label = QtGui.QLabel(self.tab)
        self.TravelMode_label.setGeometry(QtCore.QRect(350, 53, 81, 20))
        self.TravelMode_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TravelMode_label.setObjectName(_fromUtf8("TravelMode_label"))
        self.Route_Avoid_comboBox = QtGui.QComboBox(self.tab)
        self.Route_Avoid_comboBox.setGeometry(QtCore.QRect(440, 80, 111, 22))
        self.Route_Avoid_comboBox.setObjectName(_fromUtf8("Route_Avoid_comboBox"))
        self.Avoid_label = QtGui.QLabel(self.tab)
        self.Avoid_label.setGeometry(QtCore.QRect(370, 82, 61, 16))
        self.Avoid_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Avoid_label.setObjectName(_fromUtf8("Avoid_label"))
        self.Route_DistUnit_label = QtGui.QLabel(self.tab)
        self.Route_DistUnit_label.setGeometry(QtCore.QRect(340, 113, 91, 20))
        self.Route_DistUnit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Route_DistUnit_label.setObjectName(_fromUtf8("Route_DistUnit_label"))
        self.Route_DistUnit_comboBox = QtGui.QComboBox(self.tab)
        self.Route_DistUnit_comboBox.setGeometry(QtCore.QRect(440, 110, 111, 22))
        self.Route_DistUnit_comboBox.setObjectName(_fromUtf8("Route_DistUnit_comboBox"))
        self.SearchRoute_pushButton = QtGui.QPushButton(self.tab)
        self.SearchRoute_pushButton.setGeometry(QtCore.QRect(470, 180, 71, 23))
        self.SearchRoute_pushButton.setObjectName(_fromUtf8("SearchRoute_pushButton"))
        self.Route_CoorSelection_label = QtGui.QLabel(self.tab)
        self.Route_CoorSelection_label.setGeometry(QtCore.QRect(350, 150, 201, 20))
        self.Route_CoorSelection_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Route_CoorSelection_label.setObjectName(_fromUtf8("Route_CoorSelection_label"))
        self.RoutePointsFmt_2_label = QtGui.QLabel(self.tab)
        self.RoutePointsFmt_2_label.setGeometry(QtCore.QRect(10, 230, 321, 20))
        self.RoutePointsFmt_2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RoutePointsFmt_2_label.setObjectName(_fromUtf8("RoutePointsFmt_2_label"))
        self.FeatureOption_tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(GeoSearch)
        self.FeatureOption_tabWidget.setCurrentIndex(0)
        self.Result_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeoSearch)
        GeoSearch.setTabOrder(self.Addr_lineEdit, self.SearchByAddr_pushButton)
        GeoSearch.setTabOrder(self.SearchByAddr_pushButton, self.Geocoder_Addr_comboBox)
        GeoSearch.setTabOrder(self.Geocoder_Addr_comboBox, self.Latitude_lineEdit)
        GeoSearch.setTabOrder(self.Latitude_lineEdit, self.Longitude_lineEdit)
        GeoSearch.setTabOrder(self.Longitude_lineEdit, self.SearchByPt_pushButton)
        GeoSearch.setTabOrder(self.SearchByPt_pushButton, self.Geocoder_Pt_comboBox)
        GeoSearch.setTabOrder(self.Geocoder_Pt_comboBox, self.GoToGetCoorFromMapCanvasMode_pushButton)
        GeoSearch.setTabOrder(self.GoToGetCoorFromMapCanvasMode_pushButton, self.ExactOneResult_checkBox)
        GeoSearch.setTabOrder(self.ExactOneResult_checkBox, self.ObtainElevation_checkBox)
        GeoSearch.setTabOrder(self.ObtainElevation_checkBox, self.SearchOnGoogleWebMap_checkBox)
        GeoSearch.setTabOrder(self.SearchOnGoogleWebMap_checkBox, self.Result_tabWidget)
        GeoSearch.setTabOrder(self.Result_tabWidget, self.Result_listWidget)
        GeoSearch.setTabOrder(self.Result_listWidget, self.FeatureOption_tabWidget)
        GeoSearch.setTabOrder(self.FeatureOption_tabWidget, self.DistFomula_comboBox)
        GeoSearch.setTabOrder(self.DistFomula_comboBox, self.VctElliModel_comboBox)
        GeoSearch.setTabOrder(self.VctElliModel_comboBox, self.Dist_PtA_Latitude_lineEdit)
        GeoSearch.setTabOrder(self.Dist_PtA_Latitude_lineEdit, self.Dist_PtA_Longitude_lineEdit)
        GeoSearch.setTabOrder(self.Dist_PtA_Longitude_lineEdit, self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton)
        GeoSearch.setTabOrder(self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton, self.Dist_PtB_Latitude_lineEdit)
        GeoSearch.setTabOrder(self.Dist_PtB_Latitude_lineEdit, self.Dist_PtB_Longitude_lineEdit)
        GeoSearch.setTabOrder(self.Dist_PtB_Longitude_lineEdit, self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton)
        GeoSearch.setTabOrder(self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton, self.CalculateDist_pushButton)
        GeoSearch.setTabOrder(self.CalculateDist_pushButton, self.Dist_lineEdit)
        GeoSearch.setTabOrder(self.Dist_lineEdit, self.DistUnit_comboBox)
        GeoSearch.setTabOrder(self.DistUnit_comboBox, self.Bearing_lineEdit)
        GeoSearch.setTabOrder(self.Bearing_lineEdit, self.BearingUnit_comboBox)
        GeoSearch.setTabOrder(self.BearingUnit_comboBox, self.BearingIsPositiveOnly_checkBox)
        GeoSearch.setTabOrder(self.BearingIsPositiveOnly_checkBox, self.RoutePoints_textEdit)
        GeoSearch.setTabOrder(self.RoutePoints_textEdit, self.Route_GoToGetCoorFromMapCanvasMode_pushButton)
        GeoSearch.setTabOrder(self.Route_GoToGetCoorFromMapCanvasMode_pushButton, self.Route_TravelMode_comboBox)
        GeoSearch.setTabOrder(self.Route_TravelMode_comboBox, self.Route_Avoid_comboBox)
        GeoSearch.setTabOrder(self.Route_Avoid_comboBox, self.Route_DistUnit_comboBox)
        GeoSearch.setTabOrder(self.Route_DistUnit_comboBox, self.SearchRoute_pushButton)
        GeoSearch.setTabOrder(self.SearchRoute_pushButton, self.Result_textEdit)

    def retranslateUi(self, GeoSearch):
        GeoSearch.setWindowTitle(_translate("GeoSearch", "GeoSearch", None))
        self.latitude_label.setText(_translate("GeoSearch", "Latitude", None))
        self.Longitude_label.setText(_translate("GeoSearch", "Longitude", None))
        self.ExactOneResult_checkBox.setText(_translate("GeoSearch", "Exact One Result", None))
        self.SearchByAddr_pushButton.setText(_translate("GeoSearch", "Search ", None))
        self.Geocoder_Addr_label_2.setText(_translate("GeoSearch", "Geocoder", None))
        self.GoToGetCoorFromMapCanvasMode_pushButton.setText(_translate("GeoSearch", "From Map...", None))
        self.SearchByPt_pushButton.setText(_translate("GeoSearch", "Search ", None))
        self.Address_label.setText(_translate("GeoSearch", "Address", None))
        self.Geocoder_Addr_label.setText(_translate("GeoSearch", "Geocoder", None))
        self.SearchStatus_label.setText(_translate("GeoSearch", "Result", None))
        self.Result_List_label.setText(_translate("GeoSearch", "Double Click below items to zoom in", None))
        self.Result_tabWidget.setTabText(self.Result_tabWidget.indexOf(self.List_tab), _translate("GeoSearch", "List", None))
        self.Result_List_label_2.setText(_translate("GeoSearch", "For direct copy", None))
        self.Result_tabWidget.setTabText(self.Result_tabWidget.indexOf(self.Text_tab), _translate("GeoSearch", "Text", None))
        self.SearchOnGoogleWebMap_checkBox.setText(_translate("GeoSearch", "Search On Google Web Map", None))
        self.ObtainElevation_checkBox.setText(_translate("GeoSearch", "Obtain Elevation", None))
        self.ResultFmt_label.setText(_translate("GeoSearch", "(Place, (Latitude, Longitude))", None))
        self.FeatureOption_tabWidget.setTabText(self.FeatureOption_tabWidget.indexOf(self.Pt_tab), _translate("GeoSearch", "Point", None))
        self.CalculateDist_pushButton.setText(_translate("GeoSearch", "Calculate", None))
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton.setText(_translate("GeoSearch", "From Map...", None))
        self.Dist_latitude_label.setText(_translate("GeoSearch", "Latitude", None))
        self.Dist_Longitude_label.setText(_translate("GeoSearch", "Longitude", None))
        self.DistFormula_label.setText(_translate("GeoSearch", "Formula", None))
        self.VincentyElliModel_label.setText(_translate("GeoSearch", "Vincenty Ellipsoidal Model", None))
        self.PtA_label.setText(_translate("GeoSearch", "Point A:", None))
        self.PtB_label.setText(_translate("GeoSearch", "Point B:", None))
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton.setText(_translate("GeoSearch", "From Map...", None))
        self.Dist_label.setText(_translate("GeoSearch", "Distance:", None))
        self.Bearing_label.setText(_translate("GeoSearch", "Bearing:", None))
        self.BearingIsPositiveOnly_checkBox.setText(_translate("GeoSearch", "+ve only", None))
        self.FeatureOption_tabWidget.setTabText(self.FeatureOption_tabWidget.indexOf(self.Distance_tab), _translate("GeoSearch", "Distance", None))
        self.RoutePointsFmt_label.setText(_translate("GeoSearch", "(Latitude, Longitude)/Address", None))
        self.RoutePoints_label.setText(_translate("GeoSearch", "Route Points", None))
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton.setText(_translate("GeoSearch", "From Map...", None))
        self.TravelMode_label.setText(_translate("GeoSearch", "Travel Mode:", None))
        self.Avoid_label.setText(_translate("GeoSearch", "Avoid:", None))
        self.Route_DistUnit_label.setText(_translate("GeoSearch", "Distance Unit:", None))
        self.SearchRoute_pushButton.setText(_translate("GeoSearch", "Search ", None))
        self.Route_CoorSelection_label.setText(_translate("GeoSearch", "Right Click to exit points selection", None))
        self.RoutePointsFmt_2_label.setText(_translate("GeoSearch", "Point and Address can be searched togather", None))
        self.FeatureOption_tabWidget.setTabText(self.FeatureOption_tabWidget.indexOf(self.tab), _translate("GeoSearch", "Route", None))

