# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_geosearch.ui'
#
# Created: Thu Mar 13 15:40:32 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_GeoSearch(object):
    def setupUi(self, GeoSearch):
        GeoSearch.setObjectName(_fromUtf8("GeoSearch"))
        GeoSearch.resize(550, 489)
        self.FeatureOption_tabWidget = QtGui.QTabWidget(GeoSearch)
        self.FeatureOption_tabWidget.setGeometry(QtCore.QRect(0, 0, 541, 481))
        self.FeatureOption_tabWidget.setObjectName(_fromUtf8("FeatureOption_tabWidget"))
        self.Pt_tab = QtGui.QWidget()
        self.Pt_tab.setObjectName(_fromUtf8("Pt_tab"))
        self.latitude_label = QtGui.QLabel(self.Pt_tab)
        self.latitude_label.setGeometry(QtCore.QRect(190, 60, 46, 13))
        self.latitude_label.setObjectName(_fromUtf8("latitude_label"))
        self.Longitude_label = QtGui.QLabel(self.Pt_tab)
        self.Longitude_label.setGeometry(QtCore.QRect(290, 60, 51, 16))
        self.Longitude_label.setObjectName(_fromUtf8("Longitude_label"))
        self.ExactOneResult_checkBox = QtGui.QCheckBox(self.Pt_tab)
        self.ExactOneResult_checkBox.setGeometry(QtCore.QRect(250, 110, 111, 17))
        self.ExactOneResult_checkBox.setChecked(True)
        self.ExactOneResult_checkBox.setObjectName(_fromUtf8("ExactOneResult_checkBox"))
        self.SearchByAddr_pushButton = QtGui.QPushButton(self.Pt_tab)
        self.SearchByAddr_pushButton.setGeometry(QtCore.QRect(430, 30, 81, 23))
        self.SearchByAddr_pushButton.setObjectName(_fromUtf8("SearchByAddr_pushButton"))
        self.Geocoder_Addr_label_2 = QtGui.QLabel(self.Pt_tab)
        self.Geocoder_Addr_label_2.setGeometry(QtCore.QRect(50, 60, 46, 13))
        self.Geocoder_Addr_label_2.setObjectName(_fromUtf8("Geocoder_Addr_label_2"))
        self.GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.Pt_tab)
        self.GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(380, 80, 71, 23))
        self.GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Latitude_lineEdit = QtGui.QLineEdit(self.Pt_tab)
        self.Latitude_lineEdit.setGeometry(QtCore.QRect(160, 80, 101, 20))
        self.Latitude_lineEdit.setObjectName(_fromUtf8("Latitude_lineEdit"))
        self.Geocoder_Addr_comboBox = QtGui.QComboBox(self.Pt_tab)
        self.Geocoder_Addr_comboBox.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.Geocoder_Addr_comboBox.setObjectName(_fromUtf8("Geocoder_Addr_comboBox"))
        self.Addr_lineEdit = QtGui.QLineEdit(self.Pt_tab)
        self.Addr_lineEdit.setGeometry(QtCore.QRect(162, 30, 261, 20))
        self.Addr_lineEdit.setObjectName(_fromUtf8("Addr_lineEdit"))
        self.Longitude_lineEdit = QtGui.QLineEdit(self.Pt_tab)
        self.Longitude_lineEdit.setGeometry(QtCore.QRect(270, 80, 101, 20))
        self.Longitude_lineEdit.setObjectName(_fromUtf8("Longitude_lineEdit"))
        self.Geocoder_Pt_comboBox = QtGui.QComboBox(self.Pt_tab)
        self.Geocoder_Pt_comboBox.setGeometry(QtCore.QRect(10, 80, 141, 22))
        self.Geocoder_Pt_comboBox.setObjectName(_fromUtf8("Geocoder_Pt_comboBox"))
        self.SearchByPt_pushButton = QtGui.QPushButton(self.Pt_tab)
        self.SearchByPt_pushButton.setGeometry(QtCore.QRect(460, 80, 71, 23))
        self.SearchByPt_pushButton.setObjectName(_fromUtf8("SearchByPt_pushButton"))
        self.Address_label = QtGui.QLabel(self.Pt_tab)
        self.Address_label.setGeometry(QtCore.QRect(250, 10, 46, 13))
        self.Address_label.setObjectName(_fromUtf8("Address_label"))
        self.Geocoder_Addr_label = QtGui.QLabel(self.Pt_tab)
        self.Geocoder_Addr_label.setGeometry(QtCore.QRect(50, 10, 46, 13))
        self.Geocoder_Addr_label.setObjectName(_fromUtf8("Geocoder_Addr_label"))
        self.SearchStatus_label = QtGui.QLabel(self.Pt_tab)
        self.SearchStatus_label.setGeometry(QtCore.QRect(240, 160, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.SearchStatus_label.setFont(font)
        self.SearchStatus_label.setObjectName(_fromUtf8("SearchStatus_label"))
        self.Result_tabWidget = QtGui.QTabWidget(self.Pt_tab)
        self.Result_tabWidget.setGeometry(QtCore.QRect(10, 170, 511, 281))
        self.Result_tabWidget.setObjectName(_fromUtf8("Result_tabWidget"))
        self.List_tab = QtGui.QWidget()
        self.List_tab.setObjectName(_fromUtf8("List_tab"))
        self.Result_List_label = QtGui.QLabel(self.List_tab)
        self.Result_List_label.setGeometry(QtCore.QRect(10, 30, 171, 16))
        self.Result_List_label.setObjectName(_fromUtf8("Result_List_label"))
        self.Result_listWidget = QtGui.QListWidget(self.List_tab)
        self.Result_listWidget.setGeometry(QtCore.QRect(10, 50, 481, 201))
        self.Result_listWidget.setObjectName(_fromUtf8("Result_listWidget"))
        self.Result_tabWidget.addTab(self.List_tab, _fromUtf8(""))
        self.Text_tab = QtGui.QWidget()
        self.Text_tab.setObjectName(_fromUtf8("Text_tab"))
        self.Result_textEdit = QtGui.QTextEdit(self.Text_tab)
        self.Result_textEdit.setGeometry(QtCore.QRect(10, 50, 481, 201))
        self.Result_textEdit.setObjectName(_fromUtf8("Result_textEdit"))
        self.Result_List_label_2 = QtGui.QLabel(self.Text_tab)
        self.Result_List_label_2.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.Result_List_label_2.setObjectName(_fromUtf8("Result_List_label_2"))
        self.Result_tabWidget.addTab(self.Text_tab, _fromUtf8(""))
        self.SearchOnGoogleWebMap_checkBox = QtGui.QCheckBox(self.Pt_tab)
        self.SearchOnGoogleWebMap_checkBox.setEnabled(True)
        self.SearchOnGoogleWebMap_checkBox.setGeometry(QtCore.QRect(370, 110, 161, 20))
        self.SearchOnGoogleWebMap_checkBox.setChecked(False)
        self.SearchOnGoogleWebMap_checkBox.setObjectName(_fromUtf8("SearchOnGoogleWebMap_checkBox"))
        self.ObtainElevation_checkBox = QtGui.QCheckBox(self.Pt_tab)
        self.ObtainElevation_checkBox.setEnabled(True)
        self.ObtainElevation_checkBox.setGeometry(QtCore.QRect(250, 130, 111, 20))
        self.ObtainElevation_checkBox.setChecked(False)
        self.ObtainElevation_checkBox.setObjectName(_fromUtf8("ObtainElevation_checkBox"))
        self.ResultFmt_label = QtGui.QLabel(self.Pt_tab)
        self.ResultFmt_label.setGeometry(QtCore.QRect(130, 200, 261, 20))
        self.ResultFmt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultFmt_label.setObjectName(_fromUtf8("ResultFmt_label"))
        self.FeatureOption_tabWidget.addTab(self.Pt_tab, _fromUtf8(""))
        self.Distance_tab = QtGui.QWidget()
        self.Distance_tab.setObjectName(_fromUtf8("Distance_tab"))
        self.CalculateDist_pushButton = QtGui.QPushButton(self.Distance_tab)
        self.CalculateDist_pushButton.setGeometry(QtCore.QRect(230, 150, 71, 23))
        self.CalculateDist_pushButton.setObjectName(_fromUtf8("CalculateDist_pushButton"))
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.Distance_tab)
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(350, 90, 71, 23))
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Dist_latitude_label = QtGui.QLabel(self.Distance_tab)
        self.Dist_latitude_label.setGeometry(QtCore.QRect(160, 70, 46, 13))
        self.Dist_latitude_label.setObjectName(_fromUtf8("Dist_latitude_label"))
        self.Dist_Longitude_label = QtGui.QLabel(self.Distance_tab)
        self.Dist_Longitude_label.setGeometry(QtCore.QRect(260, 70, 51, 16))
        self.Dist_Longitude_label.setObjectName(_fromUtf8("Dist_Longitude_label"))
        self.DistFomula_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.DistFomula_comboBox.setGeometry(QtCore.QRect(130, 30, 141, 22))
        self.DistFomula_comboBox.setObjectName(_fromUtf8("DistFomula_comboBox"))
        self.Dist_PtA_Latitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtA_Latitude_lineEdit.setGeometry(QtCore.QRect(130, 90, 101, 20))
        self.Dist_PtA_Latitude_lineEdit.setObjectName(_fromUtf8("Dist_PtA_Latitude_lineEdit"))
        self.DistFormula_label = QtGui.QLabel(self.Distance_tab)
        self.DistFormula_label.setGeometry(QtCore.QRect(170, 10, 46, 13))
        self.DistFormula_label.setObjectName(_fromUtf8("DistFormula_label"))
        self.Dist_PtA_Longitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtA_Longitude_lineEdit.setGeometry(QtCore.QRect(240, 90, 101, 20))
        self.Dist_PtA_Longitude_lineEdit.setObjectName(_fromUtf8("Dist_PtA_Longitude_lineEdit"))
        self.VincentyElliModel_label = QtGui.QLabel(self.Distance_tab)
        self.VincentyElliModel_label.setGeometry(QtCore.QRect(290, 10, 141, 20))
        self.VincentyElliModel_label.setObjectName(_fromUtf8("VincentyElliModel_label"))
        self.VctElliModel_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.VctElliModel_comboBox.setGeometry(QtCore.QRect(280, 30, 141, 22))
        self.VctElliModel_comboBox.setObjectName(_fromUtf8("VctElliModel_comboBox"))
        self.PtA_label = QtGui.QLabel(self.Distance_tab)
        self.PtA_label.setGeometry(QtCore.QRect(90, 90, 46, 20))
        self.PtA_label.setObjectName(_fromUtf8("PtA_label"))
        self.Dist_PtB_Latitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtB_Latitude_lineEdit.setGeometry(QtCore.QRect(130, 120, 101, 20))
        self.Dist_PtB_Latitude_lineEdit.setObjectName(_fromUtf8("Dist_PtB_Latitude_lineEdit"))
        self.PtB_label = QtGui.QLabel(self.Distance_tab)
        self.PtB_label.setGeometry(QtCore.QRect(90, 120, 46, 20))
        self.PtB_label.setObjectName(_fromUtf8("PtB_label"))
        self.Dist_PtB_Longitude_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_PtB_Longitude_lineEdit.setGeometry(QtCore.QRect(240, 120, 101, 20))
        self.Dist_PtB_Longitude_lineEdit.setObjectName(_fromUtf8("Dist_PtB_Longitude_lineEdit"))
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.Distance_tab)
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(350, 120, 71, 23))
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Dist_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Dist_lineEdit.setGeometry(QtCore.QRect(190, 190, 141, 20))
        self.Dist_lineEdit.setObjectName(_fromUtf8("Dist_lineEdit"))
        self.Dist_label = QtGui.QLabel(self.Distance_tab)
        self.Dist_label.setGeometry(QtCore.QRect(140, 190, 46, 20))
        self.Dist_label.setObjectName(_fromUtf8("Dist_label"))
        self.DistUnit_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.DistUnit_comboBox.setGeometry(QtCore.QRect(340, 190, 111, 22))
        self.DistUnit_comboBox.setObjectName(_fromUtf8("DistUnit_comboBox"))
        self.Bearing_label = QtGui.QLabel(self.Distance_tab)
        self.Bearing_label.setGeometry(QtCore.QRect(140, 220, 46, 20))
        self.Bearing_label.setObjectName(_fromUtf8("Bearing_label"))
        self.Bearing_lineEdit = QtGui.QLineEdit(self.Distance_tab)
        self.Bearing_lineEdit.setGeometry(QtCore.QRect(190, 220, 141, 20))
        self.Bearing_lineEdit.setObjectName(_fromUtf8("Bearing_lineEdit"))
        self.BearingUnit_comboBox = QtGui.QComboBox(self.Distance_tab)
        self.BearingUnit_comboBox.setGeometry(QtCore.QRect(340, 220, 111, 22))
        self.BearingUnit_comboBox.setObjectName(_fromUtf8("BearingUnit_comboBox"))
        self.FeatureOption_tabWidget.addTab(self.Distance_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.RoutePoints_textEdit = QtGui.QTextEdit(self.tab)
        self.RoutePoints_textEdit.setGeometry(QtCore.QRect(10, 50, 321, 141))
        self.RoutePoints_textEdit.setObjectName(_fromUtf8("RoutePoints_textEdit"))
        self.RoutePointsFmt_label = QtGui.QLabel(self.tab)
        self.RoutePointsFmt_label.setGeometry(QtCore.QRect(40, 30, 261, 20))
        self.RoutePointsFmt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.RoutePointsFmt_label.setObjectName(_fromUtf8("RoutePointsFmt_label"))
        self.RoutePoints_label = QtGui.QLabel(self.tab)
        self.RoutePoints_label.setGeometry(QtCore.QRect(130, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RoutePoints_label.setFont(font)
        self.RoutePoints_label.setObjectName(_fromUtf8("RoutePoints_label"))
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton = QtGui.QPushButton(self.tab)
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton.setGeometry(QtCore.QRect(360, 160, 71, 23))
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton.setObjectName(_fromUtf8("Route_GoToGetCoorFromMapCanvasMode_pushButton"))
        self.Route_TravelMode_comboBox = QtGui.QComboBox(self.tab)
        self.Route_TravelMode_comboBox.setGeometry(QtCore.QRect(410, 50, 111, 22))
        self.Route_TravelMode_comboBox.setObjectName(_fromUtf8("Route_TravelMode_comboBox"))
        self.TravelMode_label = QtGui.QLabel(self.tab)
        self.TravelMode_label.setGeometry(QtCore.QRect(340, 53, 61, 16))
        self.TravelMode_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TravelMode_label.setObjectName(_fromUtf8("TravelMode_label"))
        self.Route_Avoid_comboBox = QtGui.QComboBox(self.tab)
        self.Route_Avoid_comboBox.setGeometry(QtCore.QRect(410, 80, 111, 22))
        self.Route_Avoid_comboBox.setObjectName(_fromUtf8("Route_Avoid_comboBox"))
        self.Avoid_label = QtGui.QLabel(self.tab)
        self.Avoid_label.setGeometry(QtCore.QRect(340, 82, 61, 16))
        self.Avoid_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Avoid_label.setObjectName(_fromUtf8("Avoid_label"))
        self.Route_DistUnit_label = QtGui.QLabel(self.tab)
        self.Route_DistUnit_label.setGeometry(QtCore.QRect(330, 113, 71, 16))
        self.Route_DistUnit_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Route_DistUnit_label.setObjectName(_fromUtf8("Route_DistUnit_label"))
        self.Route_DistUnit_comboBox = QtGui.QComboBox(self.tab)
        self.Route_DistUnit_comboBox.setGeometry(QtCore.QRect(410, 110, 111, 22))
        self.Route_DistUnit_comboBox.setObjectName(_fromUtf8("Route_DistUnit_comboBox"))
        self.SearchRoute_pushButton = QtGui.QPushButton(self.tab)
        self.SearchRoute_pushButton.setGeometry(QtCore.QRect(440, 160, 71, 23))
        self.SearchRoute_pushButton.setObjectName(_fromUtf8("SearchRoute_pushButton"))
        self.Route_CoorSelection_label = QtGui.QLabel(self.tab)
        self.Route_CoorSelection_label.setGeometry(QtCore.QRect(350, 140, 161, 20))
        self.Route_CoorSelection_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Route_CoorSelection_label.setObjectName(_fromUtf8("Route_CoorSelection_label"))
        self.FeatureOption_tabWidget.addTab(self.tab, _fromUtf8(""))

        self.retranslateUi(GeoSearch)
        self.FeatureOption_tabWidget.setCurrentIndex(0)
        self.Result_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeoSearch)

    def retranslateUi(self, GeoSearch):
        GeoSearch.setWindowTitle(QtGui.QApplication.translate("GeoSearch", "GeoSearch", None, QtGui.QApplication.UnicodeUTF8))
        self.latitude_label.setText(QtGui.QApplication.translate("GeoSearch", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.Longitude_label.setText(QtGui.QApplication.translate("GeoSearch", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.ExactOneResult_checkBox.setText(QtGui.QApplication.translate("GeoSearch", "Exact One Result", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchByAddr_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "Search ", None, QtGui.QApplication.UnicodeUTF8))
        self.Geocoder_Addr_label_2.setText(QtGui.QApplication.translate("GeoSearch", "Geocoder", None, QtGui.QApplication.UnicodeUTF8))
        self.GoToGetCoorFromMapCanvasMode_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "From Map...", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchByPt_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "Search ", None, QtGui.QApplication.UnicodeUTF8))
        self.Address_label.setText(QtGui.QApplication.translate("GeoSearch", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.Geocoder_Addr_label.setText(QtGui.QApplication.translate("GeoSearch", "Geocoder", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchStatus_label.setText(QtGui.QApplication.translate("GeoSearch", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.Result_List_label.setText(QtGui.QApplication.translate("GeoSearch", "Double Click below items to zoom in", None, QtGui.QApplication.UnicodeUTF8))
        self.Result_tabWidget.setTabText(self.Result_tabWidget.indexOf(self.List_tab), QtGui.QApplication.translate("GeoSearch", "List", None, QtGui.QApplication.UnicodeUTF8))
        self.Result_List_label_2.setText(QtGui.QApplication.translate("GeoSearch", "For direct copy", None, QtGui.QApplication.UnicodeUTF8))
        self.Result_tabWidget.setTabText(self.Result_tabWidget.indexOf(self.Text_tab), QtGui.QApplication.translate("GeoSearch", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchOnGoogleWebMap_checkBox.setText(QtGui.QApplication.translate("GeoSearch", "Search On Google Web Map", None, QtGui.QApplication.UnicodeUTF8))
        self.ObtainElevation_checkBox.setText(QtGui.QApplication.translate("GeoSearch", "Obtain Elevation", None, QtGui.QApplication.UnicodeUTF8))
        self.ResultFmt_label.setText(QtGui.QApplication.translate("GeoSearch", "(Place, (Latitude, Longitude))", None, QtGui.QApplication.UnicodeUTF8))
        self.FeatureOption_tabWidget.setTabText(self.FeatureOption_tabWidget.indexOf(self.Pt_tab), QtGui.QApplication.translate("GeoSearch", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.CalculateDist_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.Dist_PtA_GoToGetCoorFromMapCanvasMode_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "From Map...", None, QtGui.QApplication.UnicodeUTF8))
        self.Dist_latitude_label.setText(QtGui.QApplication.translate("GeoSearch", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.Dist_Longitude_label.setText(QtGui.QApplication.translate("GeoSearch", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.DistFormula_label.setText(QtGui.QApplication.translate("GeoSearch", "Formula", None, QtGui.QApplication.UnicodeUTF8))
        self.VincentyElliModel_label.setText(QtGui.QApplication.translate("GeoSearch", "Vincenty Ellipsoidal Model", None, QtGui.QApplication.UnicodeUTF8))
        self.PtA_label.setText(QtGui.QApplication.translate("GeoSearch", "Point A:", None, QtGui.QApplication.UnicodeUTF8))
        self.PtB_label.setText(QtGui.QApplication.translate("GeoSearch", "Point B:", None, QtGui.QApplication.UnicodeUTF8))
        self.Dist_PtB_GoToGetCoorFromMapCanvasMode_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "From Map...", None, QtGui.QApplication.UnicodeUTF8))
        self.Dist_label.setText(QtGui.QApplication.translate("GeoSearch", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.Bearing_label.setText(QtGui.QApplication.translate("GeoSearch", "Bearing:", None, QtGui.QApplication.UnicodeUTF8))
        self.FeatureOption_tabWidget.setTabText(self.FeatureOption_tabWidget.indexOf(self.Distance_tab), QtGui.QApplication.translate("GeoSearch", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.RoutePointsFmt_label.setText(QtGui.QApplication.translate("GeoSearch", "Latitude, Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.RoutePoints_label.setText(QtGui.QApplication.translate("GeoSearch", "Route Points", None, QtGui.QApplication.UnicodeUTF8))
        self.Route_GoToGetCoorFromMapCanvasMode_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "From Map...", None, QtGui.QApplication.UnicodeUTF8))
        self.TravelMode_label.setText(QtGui.QApplication.translate("GeoSearch", "Travel Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.Avoid_label.setText(QtGui.QApplication.translate("GeoSearch", "Avoid:", None, QtGui.QApplication.UnicodeUTF8))
        self.Route_DistUnit_label.setText(QtGui.QApplication.translate("GeoSearch", "Distance Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.SearchRoute_pushButton.setText(QtGui.QApplication.translate("GeoSearch", "Search ", None, QtGui.QApplication.UnicodeUTF8))
        self.Route_CoorSelection_label.setText(QtGui.QApplication.translate("GeoSearch", "Right Click to exit points selection", None, QtGui.QApplication.UnicodeUTF8))
        self.FeatureOption_tabWidget.setTabText(self.FeatureOption_tabWidget.indexOf(self.tab), QtGui.QApplication.translate("GeoSearch", "Route", None, QtGui.QApplication.UnicodeUTF8))

